import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Link,
} from "@react-pdf/renderer";
import type { AuditResult } from "@/lib/api/audit";
import { calculateBlindLensScore, getScoreVerdict } from "./scoreUtils";
import { pdfColors as c } from "./pdfTheme";

const styles = StyleSheet.create({
  page: {
    backgroundColor: c.background,
    color: c.foreground,
    paddingTop: 48,
    paddingBottom: 64,
    paddingHorizontal: 48,
    fontFamily: "Helvetica",
    fontSize: 11,
    lineHeight: 1.5,
  },
  wordmark: { fontSize: 14, color: c.accent, fontFamily: "Helvetica-Bold", letterSpacing: 1 },
  coverWrap: { marginTop: 80, alignItems: "flex-start" },
  coverTitle: { fontSize: 32, fontFamily: "Helvetica-Bold", color: c.foreground, marginBottom: 16 },
  coverUrl: { fontSize: 12, color: c.muted, marginBottom: 4 },
  coverDate: { fontSize: 10, color: c.muted, marginBottom: 40 },
  scoreNumber: { fontSize: 96, fontFamily: "Helvetica-Bold", lineHeight: 1 },
  verdictLabel: { fontSize: 24, fontFamily: "Helvetica-Bold", marginTop: 8 },
  scoreOutOf: { fontSize: 11, color: c.muted, marginTop: 4 },
  srEquivalent: { fontSize: 9, color: c.muted, marginTop: 12 },
  sectionHeading: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: c.foreground,
    marginBottom: 12,
    paddingLeft: 10,
    borderLeftWidth: 3,
    borderLeftColor: c.accent,
    borderLeftStyle: "solid",
  },
  sectionWrap: { marginTop: 24 },
  verdictQuote: {
    fontStyle: "italic",
    fontSize: 13,
    color: c.foreground,
    backgroundColor: c.surface,
    borderLeftWidth: 3,
    borderLeftColor: c.accent,
    borderLeftStyle: "solid",
    padding: 14,
    lineHeight: 1.6,
  },
  statsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  statBox: {
    flexGrow: 1,
    minWidth: 90,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    borderStyle: "solid",
    borderRadius: 6,
    padding: 10,
    alignItems: "center",
  },
  statNum: { fontSize: 22, fontFamily: "Helvetica-Bold" },
  statLabel: { fontSize: 8, color: c.muted, marginTop: 4, textAlign: "center" },
  issue: {
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    borderStyle: "solid",
    borderRadius: 6,
    padding: 12,
    marginBottom: 8,
  },
  severityTag: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
    marginBottom: 6,
    alignSelf: "flex-start",
  },
  issueTitle: { fontSize: 12, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  issueQuote: { fontSize: 10, color: c.muted, fontStyle: "italic", lineHeight: 1.5 },
  lhItem: {
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    borderStyle: "solid",
    borderRadius: 4,
    padding: 8,
    marginBottom: 6,
  },
  lhTitle: { fontSize: 10, fontFamily: "Helvetica-Bold", color: c.foreground },
  lhValue: { fontSize: 9, color: c.muted, marginTop: 2 },
  attribution: { fontSize: 9, color: c.muted, marginTop: 10 },
  link: { color: c.accent, textDecoration: "underline" },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: c.muted,
    borderTopWidth: 1,
    borderTopColor: c.border,
    borderTopStyle: "solid",
    paddingTop: 8,
  },
});

const severityColors: Record<string, { bg: string; fg: string }> = {
  "🔴 Red Flag": { bg: "#3a0d0d", fg: c.destructive },
  "🟡 It's Complicated": { bg: "#3a2a0d", fg: c.warning },
  "⚪ Minor Ick": { bg: "#1f2937", fg: c.muted },
};

interface Props {
  result: AuditResult;
  domain: string;
  dateStr: string;
  generatedAt: string;
}

const Footer = () => (
  <View style={styles.footer} fixed>
    <Text>
      Generated by Blind Lens — See your website through the blind lens. blind-lens-audits.lovable.app
    </Text>
    <Text
      render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
    />
  </View>
);

export const BlindLensReportPdf = ({ result, domain, dateStr, generatedAt }: Props) => {
  const score = calculateBlindLensScore(result.waveStats, result.lighthouse);
  const verdict = getScoreVerdict(score);

  return (
    <Document
      title={`Blind Lens Accessibility Audit — ${domain} — ${dateStr}`}
      author="Blind Lens"
      subject="Accessibility audit report"
      language="en"
    >
      {/* Page 1: Cover */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.wordmark}>BLIND LENS</Text>
        <View style={styles.coverWrap}>
          <Text style={styles.coverTitle}>Accessibility Audit Report</Text>
          <Text style={styles.coverUrl}>{result.url}</Text>
          <Text style={styles.coverDate}>Audited {generatedAt}</Text>

          <Text style={[styles.scoreNumber, { color: verdict.hex }]}>{score}</Text>
          <Text style={[styles.verdictLabel, { color: verdict.hex }]}>{verdict.label}</Text>
          <Text style={styles.scoreOutOf}>Blind Lens Score · out of 100</Text>
          <Text style={styles.srEquivalent}>
            Blind Lens Score: {score} out of 100. Verdict: {verdict.label}.
          </Text>
        </View>
        <Footer />
      </Page>

      {/* Page 2+: Verdict, WAVE, Lighthouse */}
      <Page size="A4" style={styles.page}>
        {result.closingSummary ? (
          <View style={styles.sectionWrap} wrap={false}>
            <Text style={styles.sectionHeading}>Wikan's Verdict</Text>
            <Text style={styles.verdictQuote}>"{result.closingSummary}"</Text>
          </View>
        ) : null}

        <View style={styles.sectionWrap}>
          <Text style={styles.sectionHeading}>WAVE Findings</Text>
          <View style={styles.statsRow}>
            {[
              { n: result.waveStats.totalErrors, l: "Errors", color: c.destructive },
              { n: result.waveStats.contrastErrors, l: "Contrast Failures", color: c.warning },
              { n: result.waveStats.alerts, l: "Alerts", color: c.warning },
              { n: result.waveStats.features, l: "Positive Features", color: c.accent },
              { n: result.waveStats.structuralElements, l: "Structural Elements", color: c.primary },
            ].map((s) => (
              <View key={s.l} style={styles.statBox}>
                <Text style={[styles.statNum, { color: s.color }]}>{s.n}</Text>
                <Text style={styles.statLabel}>{s.l}</Text>
              </View>
            ))}
          </View>

          {result.issues.map((issue, i) => {
            const sc = severityColors[issue.severity] ?? severityColors["⚪ Minor Ick"];
            return (
              <View key={i} style={styles.issue} wrap={false}>
                <Text style={[styles.severityTag, { backgroundColor: sc.bg, color: sc.fg }]}>
                  {issue.severity}
                </Text>
                <Text style={styles.issueTitle}>{issue.title}</Text>
                <Text style={styles.issueQuote}>"{issue.blindLensCommentary}"</Text>
              </View>
            );
          })}

          <Text style={styles.attribution}>
            WAVE accessibility data provided by{" "}
            <Link src="https://wave.webaim.org" style={styles.link}>WebAIM (wave.webaim.org)</Link>.
          </Text>
        </View>

        {result.lighthouse && result.lighthouse.failedAudits.length > 0 ? (
          <View style={styles.sectionWrap}>
            <Text style={styles.sectionHeading}>Additional Accessibility Checks (Lighthouse)</Text>
            {result.lighthouse.failedAudits.map((a) => (
              <View key={a.id} style={styles.lhItem} wrap={false}>
                <Text style={styles.lhTitle}>{a.title}</Text>
                {a.displayValue ? <Text style={styles.lhValue}>{a.displayValue}</Text> : null}
              </View>
            ))}
          </View>
        ) : null}

        <Footer />
      </Page>
    </Document>
  );
};

export default BlindLensReportPdf;
